joint_state_controller:
  JointStateController:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50
gra_base:
  ackermann_steering_controller:
    type: "ackermann_steering_controller/AckermannSteeringController"
    rear_wheel: 'rear_wheel_joint'
    front_steer: 'front_steer_joint'
